# Generated by Django 4.2.17 on 2024-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
